### ISSUE TITLE
EGUI File Open/Save Dialog

### ISSUE THREAD

**Issue by Lowentwickler** [lowenware/dotrix#100]
Suggestion:
- For the beginning it can display files and folders of one directory
- Default directory is current working directory
- By `...` on top you can go up 
- Can be done as an EGUI widget
- Can be a part of a new module `extras` in `dotrix_egui` crate

**Comment by Xaniaro** [comment]
Hi, thanks for your reply.
Fell free to share your code if you want, I can take some inspiration.

My current progress looks like this
![dialog](https://user-images.githubusercontent.com/72392311/136583331-475eaab2-2722-49b8-b9af-4e5d641d3f8c.png)

Also experimenting with drag & drop

https://user-images.githubusercontent.com/72392311/136585238-1c2bae65-5917-41d8-adb3-06d71bd18825.mp4

**Comment by Lowentwickler** [comment]
@Xaniaro I like it :) I think `New Folder` button is missing.

@tree786 Thanks for sharing!
