### ISSUE TITLE
Hi, is this a fork of the Bevy game engine?

### ISSUE THREAD

**Issue by Joe23232** [lowenware/dotrix#117]
Hey man, is this a fork of the [Bevy game engine](https://bevyengine.org/)?

Addtionally do you provide a GUI game editor, something like [Godot](https://godotengine.org/)?

**Comment by Lowentwickler** [comment]
Hey, no it is not a fork. Dotrix is written from scratch. But concept `system is a function` was inspired. However, our systems can have own Context.

We are working on editor, but we are in the very beginning:
https://github.com/lowenware/dotrix/tree/feat/editor

**Comment by Joe23232** [comment]
@Lowentwickler Interesting mate. So in terms of performance wise which one would be better Dotrix or Bevy, sorry I am just looking for the right game engine that is all :)

**Comment by Lowentwickler** [comment]
Yes, [here](https://camo.githubusercontent.com/961c2fb8be762cac9ba53477a0e72c30c28c02e88ab47d0c642c226a52b4f630/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3730363537353036383531353533323835312e7376673f6c6162656c3d266c6f676f3d646973636f7264266c6f676f436f6c6f723d66666666666626636f6c6f723d373338394438266c6162656c436f6c6f723d364137454332)

**Comment by Joe23232** [comment]
Ok thanks :)
