### ISSUE TITLE
describe platform specific dependencies in readme.md

### ISSUE THREAD

**Issue by ZKpot** [lowenware/dotrix#15]
add description of dependencies that are not managed by cargo
- [ ] windows
- [ ] linux
- [ ] macos

**Comment by ZKpot** [comment]
To run WGPU on Windows https://vulkan.lunarg.com/sdk/home should be installed

**Comment by Lowentwickler** [comment]
Shaderc is not longer a requirement and README.me now has an explanation section, so I close this.
