### ISSUE TITLE
Failure to link on Windows

### ISSUE THREAD

**Issue by kvark** [lowenware/dotrix#21]
Lookslike `shaderc-sys` conflicts with `spirv-cross`:
```
  = note: libspirv_cross-891e604f7d6a10f0.rlib(wrapper.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_cross.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_cross_util.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_glsl.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_hlsl.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_msl.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_cfg.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_cross_parsed_ir.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          libspirv_cross-891e604f7d6a10f0.rlib(spirv_parser.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libshaderc_sys-ce3bd0ba8b42d654.rlib(shaderc.obj)
          LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
          C:\Users\dzmitry\Code\dotrix\target\release\examples\fox.exe : fatal error LNK1319: 9 mismatches detected
```

**Comment by Lowentwickler** [comment]
how did you get this output?

**Comment by kvark** [comment]
Just doing `cargo run --example fox`, and this is the error from linking on the console.

**Comment by Lowentwickler** [comment]
We should probably consider use of precompiled shaders. You probably have older version of Vulkan SDK or maybe even self-compiled shaderc library.

**Comment by kvark** [comment]
I don't have `shaderrc` installed by any means, it's something your dependencies bring. Does it require Vulkan SDK? I'd be surprised if it does.

**Comment by Lowentwickler** [comment]
Rust `shaderc` is just a binding. The library itself is distributed as a part of Vulkan SDK or can be built as dev-dependency.

**Comment by kvark** [comment]
You are correct. It uses the binary from Vulkan SDK if it sees it. Otherwise, it builds it. I'll try updating the SDK.

**Comment by Lowentwickler** [comment]
@kvark did the update of SDK help?

**Comment by kvark** [comment]
Side-stepping the question a bit (not running Windows often): what if it does? Do you require Vulkan SDK to be installed?
Generally in Rust we don't require the SDK to compile and run applications. Hence, shaderc tries to build it from scratch (and fails) if it can't find one.

**Comment by Lowentwickler** [comment]
At this moment we don't have precompiled shaders, so you need a shaderc installed.

But it is already planned and in nearest future I will hide compilation of shaders by a macro and provide precompiled shaders using `glslang` just as you do for the `wgpu`

**Comment by kvark** [comment]
In the near future, hopefully there will be an opportunity to port your shaders to WGSL, or to use Naga for converting from GLSL. We've already starting converting wgpu-rs shaders, but it's still too early to recommend you diving into it.
I'll reach back as soon as I'm testing on Windows. Sorry about the delay!

**Comment by Lowentwickler** [comment]
I am looking forward Naga actually. 
No stress.

**Comment by Lowentwickler** [comment]
So after this [commit](https://github.com/lowenware/dotrix/commit/f124434bc984069cfd9591480399ad0ba8382376) ´shaderc´ is an optional dependency, that could be enabled by appropriate feature flag. By default renderers are using precompiled SPIR-V shaders. 

README.md is populated with appropriate section.

**Comment by Lowentwickler** [comment]
We are on wgpu 0.7.0 now and I believe the issue can be closed.
