### ISSUE TITLE
Problems with Lighting

### ISSUE THREAD

**Issue by Xaniaro** [lowenware/dotrix#44]
* [x] 1) Alpha does not work on light
How to reproduce:
in `example/egui` add
```
ui.label("Alpha");
ui.add(Slider::f32(&mut editor.light_color.w, 0.0..=3.0).text(""));
if ui.button("↺").on_hover_text("Reset value").clicked {
    editor.light_color.w = 1.0;
};
ui.end_row();
```
into `settings.rs/ui` (after line 192)

* [x] 2) Enable/disable feature and multiple lights
I only added `pub enabled: bool`, into `dotrix_core\src\renderer\light.rs`, it multiple lights stopped working correctly.

* [x] 3) Color struct and light constructor
instead of
```
world.spawn(Some((Light::white([x, y, z]),)));
```
would like to have something like
```
world.spawn(Some(Light::new(Vec3, Color)));
```

**Comment by Xaniaro** [comment]
>  1) Alpha does not work on light
Tryed in Unity. Alpha doesn't work too. There is intensity parameter that multiply color value.

**Comment by Xaniaro** [comment]
Alpha is now ignored, added intensity parameter to control it. Also considering to have multiple Color structures RGB, RGBA, maybe more

**Comment by Lowentwickler** [comment]
Would be nice to add a screenshot of Light Example to the Readme.
