### ISSUE TITLE
Ligthting refactoring

### ISSUE THREAD

**Issue by Lowentwickler** [lowenware/dotrix#52]
Implement different types of lights and possibility to disable them

**Comment by Xaniaro** [comment]
Can you please more describe what we need?
We have `Ambient, Directional, Point, Simple and Spot` light components in `feature/light` and everyone except `Ambient` have `enabled` property, so you can disable them with `enabled = false`

**Comment by Lowentwickler** [comment]
:) I just made an issue to link it to your PR backwards. That is why the task is so weak. Because it is solved already :)
