### ISSUE TITLE
Hide the pointer when the game window is active

### ISSUE THREAD

**Issue by ZKpot** [lowenware/dotrix#57]
- [x] it should be possible to hide pointer when the application window is active
- [ ] it should be possible to set custom cursor pointer
- [x] it should be possible to enable fullscreen mode
- [x] in fullscreen mode, we should be able to deal with mouse delta even running out of the screen. To be able to scroll, move screen etc.

**Comment by Xaniaro** [comment]
Please observe [Window Service with example #62](https://github.com/lowenware/dotrix/pull/62)
Everything except custom mouse cursor is done.

Check `dotrix\examples\window\camera.rs` in example 
when RMB is pressed: cursor is hidden and camera starts moving
when RMB is released: cursor is shown and is returned to position when it was before hiding

**Comment by Lowentwickler** [comment]
Custom cursor pointer implementation is postponed due to low priority.
