### ISSUE TITLE
ECS crash

### ISSUE THREAD

**Issue by leudz** [lowenware/dotrix#60]
Hi, I just discovered Dotrix today and looking at the api I tried a few things.

```rust
fn oops(mut world: Mut<World>) {
    std::thread::spawn(move || loop {
        world.spawn(std::iter::once((0usize,)));
    });
}

fn oops2(mut world: Mut<World>) {
    world.spawn(std::iter::once((0usize,)));

    for (i1,) in world.query::<(&mut usize,)>() {
        for (i2,) in world.query::<(&mut usize,)>() {
            *i1 += 1;
            *i2 += 1;

            dbg!((&i1, &i2));
        }
    }
}

fn main() {
    Dotrix::application("Oops")
        .with_system(System::from(oops))
        .with_service(World::new())
        .run()
}
```

On my computer `oops` fails with either `STATUS_STACK_BUFFER_OVERRUN` or `STATUS_HEAP_CORRUPTION`.

Two consecutive prints of `oops2` can look like this:

```txt
[src\main.rs:21] (&i1, &i2) = (
    61,
    15,
)
[src\main.rs:21] (&i1, &i2) = (
    16,
    272,
)
```

**Comment by Xaniaro** [comment]
Thank you for reporting the issue.

The developer will check it as soon as he return from the vacation, after 12.4.

**Comment by Lowentwickler** [comment]
Hi,

this is not how it is supposed to be used:
```
fn oops(mut world: Mut<World>) {
    std::thread::spawn(move || loop {
        world.spawn(std::iter::once((0usize,)));
    });
}
```

As a system `oops` will be called periodically and on each call it will spawn a thread, and each thread will endlessly spawn an entity. 

Regarding `oops2`, I don't see an issue here. I can even imagine conditions under which the output could be legal.

Maybe you can provide some more  information on what do you want to achieve?
