### ISSUE TITLE
Add world.exile method to remove entities

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#64]
Hallo

I understand that you can spawn entities in the world by using the .spawn() function, but is there (or will there be) a '.remove()' function on the World service, in order to delete that entity once it is not needed? Btw I am new to using the ECS, so maybe i have missed something (please let me know if there is workaround as i am clueless). 
I know there is a '.remove()' function for the Assets service, but that is not what I am after (since that removes the asset, not the specific entities which can have that asset component)

Gracias

**Comment by Lowentwickler** [comment]
Hello,

you did not miss anything, there is indeed no remove function, but there will be one soon. I had two different ideas, how the removal should work and decided to wait for the use case to decide. The use case raised during the terrain development, so it is a `coming soon` feature. 

De nada :)

**Comment by tree786** [comment]
Hi, thanks you, very good to hear! :)
