### ISSUE TITLE
Control over individual camera X,Y,Z rot and clipping dist

### ISSUE THREAD

**Issue by mhd1msyb** [lowenware/dotrix#66]
Ahoj

Regarding the `Camera `service, I understand that you can call the function `y_angle` to rotate along y-axis, and the function `xz_angle` rotate along both X and Z at the same time (i.e. in same plane). However I would like to have individual control over `X` and `Z` rotations independently (eg like freecam) , is possible to do this?
Is there also function/method for set max clip distance (i could not find in the API)?

Gracias

**Comment by Lowentwickler** [comment]
Hi, 

the namings must be kinda missleading. Lets pretend, we speak about the camera in game with 1st person look. When you turn around, you change `y_angle`. It is not an angle around Y axis (not yaw), but an angle around Vertical virtual axis passing through target `look_at` point. 

The `xz_angle` is an angle of camera that changes when you look from the floor to ceilings or vice versa.  Same as pitch actually. 

It is enough to build a free flying camera, 3rd or 1st person look. If you need `roll` functionality, it is slightly another story. Do you need it?

Do you mean configuration of the projection matrix by the `max clip distance`? If so, it is hard coded, but it is not hard to make configurable. Let me know if you need it.

Cheers

**Comment by mhd1msyb** [comment]
Hi
 
Ok I see, thanks for clarifying. Yeah it was roll angle I looking for but I am not sure how to implement it . I currently not need it but thought it could be useful in future purposes 
I might have a look for projection matrix settings to see adjust , but currently i think the hard-coded value is fine for my cases

Thanks
