### ISSUE TITLE
Add support for materials with at least albedo color

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#67]
Hallo

Here is simple car game i working on (video preview) [https://tmpfiles.org/dl/38832/uyjuyy.mp4](https://tmpfiles.org/dl/38832/uyjuyy.mp4). You can spawn unlimited number of cars and enter/exit and riding them. The vehicle mechanics not accurate from engineering perspective (ie doesn't use any tire model/car wind forces).
But regarding a new feature: It would be nice to be able to change the material/color of the car/object in realtime, but as i understand, you need to write shader for this? Is there future plan for implementing method on the `Model` so that can change the color of mesh in realtimes? I currently not know how to make glsl shader for changing color 

Gracias

**Comment by Lowentwickler** [comment]
Hi!

The link says 404.

We don't have model colouring at this moment and rely on textures. You can create several single color textures (or generate them and store in assets manually), and assign them to models (or change them) on the fly. 

If you need more info on it, let me know.

Cheers!

**Comment by tree786** [comment]
Hi
apologies for broken link. Here is updated [https://github.com/tree786/test/blob/main/tewst.mp4](https://github.com/tree786/test/blob/main/tewst.mp4)
Ok no problem, i currently will use the textures for material. Thanks!
