### ISSUE TITLE
Better way of generating big amounts of geomtery in realtime (i.e. for particle trails/skid marks)

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#69]
Hallo

I have implemented basic skid marks in my basic car game
![skid](https://user-images.githubusercontent.com/40580296/119569148-34317300-bd63-11eb-9e3b-3d4058131639.png)
It work very  well, however I believe the method is very inefficient. I explain below:

- First I initialize world (called once on Startup) with skid texture i.e. something like
```
-     let load_texture=assets.import("./skid_texture.png"); 
      let skid_texture=assets.register::<Texture>("skid_texture");
```
 

- Then I  generate a mesh with the new skid mesh coordinates like this :
```
- let mesh=Mesh{
            positions:vec![v1,v2,v3,v4,v5,v6],
            normals:Some(vec![[0.0,1.0,0.0],[0.0,1.0,0.0],[0.0,1.0,0.0],    [0.0,1.0,0.0],[0.0,1.0,0.0],[0.0,1.0,0.0]]),
            uvs:Some(vec![[0.0,0.0],[0.0,1.0],[1.0,1.0],    [0.0,0.0],[0.0,1.0],[1.0,1.0]]),
            ..Default::default()

        };
```

- I register this mesh as well `assets.store_as::<Mesh>(mesh,"skid");`
- Finally I add this mesh to the `Model` component using the spawn method, i.e. : 
- ```
        world.spawn( Some((
            Model{mesh: skid_mesh,
                texture:skid_texture),
                ..Default::default()

                },
            ),
        ));
    }
```
```
However I thought it would be more optimal to , instead of registering this new mesh every frame, register it once but modify the `mesh.positions` vertex positions. Do you know of a better method to achieve this , i.e. generate lots of new meshes every frame with new vertex coords from one registered mesh (registered on Startup), rather than registering a new mesh every frame? 
Hop i explained clearly.. !

Gracias

**Comment by Lowentwickler** [comment]
Hi! 

On every frame when you need to update the skid mesh, you could do following:
```
let mesh_id = assets.register::<Mesh>::("skid");
if let Some(mut mesh) = assets.get_mut(mesh_id) {
  mesh.unload();
  // set what was chnaged
  mesh.positions = ...
  mesh.normals = ...
  mesh.uvs = ...
}
```

This should work. I did similar things in the Editor project.

Cheers!

P.S. Thank you very much for using our engine!

**Comment by tree786** [comment]
Hi
Thanks very much for the advice! I will try this out! :)

Thanks
