### ISSUE TITLE
How to make fragment shaders for screen pixels?

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#70]
Hallo

I wasn't sure where to ask this so I open a new thread 
With regards to shaders, I'd like to use glsl shaders to change the color of screen pixels (e.g. make blur screen filter and lens distortion shader effects). However, how would I then use this shader and integrate it within the dotrix in order to apply to screen pixels?
For example , if i have the following openGL glsl shader code below :

```
out vec4 colorOut;
 
void main()
{
    colorOut = vec4(1.0, 0.0, 0.0, 1.0);
}
```

Do I first compile this to spir-v to make it vulkan compatible? And then how would i add this compiled shader to dotrix to affect all screen color pixels? Also , if i have uniforms in my shader, how can i access and modify them via dotrix ? Apologies for my lack of info on the topic, and shaders in general I am very new to it!

Thanks for answers my previous questions as well!

**Comment by Lowentwickler** [comment]
Hello,

This feature was recently implemented, but as a side effect of pipelines refactoring, so it was never tested.

1. In `dotrix_core::renderer::pipeline` you can find methods for construction of existing pipelines. Check them and choose one that suits more to the model which shader you want to customize. It should either be a static model or skinned model (supports skeletal animation).
2. Now lets pretend you need a static model. Check methods `new_for_static_model` and `default_for_static_model`. You will need to implement your own Pipeline constructor that will use `new_for_static_model` inside. The method takes compiled shaders as parameters.
3. In your startup system create the pipeline and add it to `Renderer` using `add_pipeline` method and store returned id somewhere.
4. Then when you spawn an entity in the world, set `pipeline` property of the Model to the Id obtained from previous method. This should make it work.

Now to the shader. If you use glsl, you will have to compile it. Check existing shaders in `https://github.com/lowenware/dotrix/tree/main/dotrix_core/src/renderer/shaders` there are two types: .glsl and .wgsl. In future we will port them all to .wgsl. You can also check how to compile .glsl ones in the [Makefile](https://github.com/lowenware/dotrix/blob/main/Makefile), you will need to insall 3rd party tools for that.

**Comment by tree786** [comment]
Hi
Thanks a lot for the info! I think I will leave this out for time being, I am not too familiar with shaders as a whole and pipelines. hopefully i can try it in future !

Thanks

**Comment by Lowentwickler** [comment]
Sure thing, I will close this for now
