### ISSUE TITLE
Is 'camera.view()' matrix same as the world-to-camera space matrix?

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#74]
Hi again

I am trying to get the 2D screen coordinates of a 3d object, and I am using the following methods:
```
let pos=Vec3::new(0.0,10.0,0.0); // position of the object that I want to project on the screen (get it's 2D screen coordinate)
let matrix_mult=camera.view()*Vec4::new(pos.x, pos.y, pos.z,1.0); // I multiply the camera view matrix by pos vector to get new position in camera space coordinate
let screen_coord=Vec2::new( (matrix_mult.x+1.0*display_width/2.0), (matrix_mult.y+1.0*display_height/2.0) ); 
```
But is the `camera.view()` in local camera coordinate system (i.e. world-to-camera space)? Maybe I am doing it wrong, as when I use the method above I get very large values for screen coordinate. 
Thanks !

**Comment by Lowentwickler** [comment]
Hi! 

Try investigate the [mouse ray implementation](https://github.com/lowenware/dotrix/blob/main/dotrix_core/src/input/ray.rs) that is a part of dotrix. We use it in the [editor project](https://github.com/lowenware/dotrix-editor/blob/main/src/brush.rs) and it works. 

Cheers!

**Comment by tree786** [comment]
Hi :) Thanks, I have checked out the editor implementation for mouse ray and it almost works (i need to tweak some values in my game i think). I close now . Thanks!
