### ISSUE TITLE
'Failed to find an appropiate adapter' on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#75]
Hello

Yesterday I installed fresh copy of ubuntu 20.04 LTS , and I have tried to run simple dotrix projects using `cargo run --release`, but I am getting the following error:
```
thread 'main' panicked at 'Failed to find an appropiate adapter', /home/mm/.cargo/registry/src/github.com-1ecc6299db9ec823/dotrix_core-0.3.0/src/application.rs:190:10
```
I understand this is related to the graphics card, so I tried installing various nvidia versions (I tried nvidia metapackage 460/465/450 and 340.108), however it didn't resolve the issue (i have GTX 760). Is it related to a vulkan dependencies not being installed on my computer ?  Or is it not detecting my graphic card at all, and instead falling back to integrated graphics on my cpu? 

Here is the test file if you want to test [issue.zip](https://github.com/lowenware/dotrix/files/6612965/issue.zip)

Thanks

**Comment by Lowentwickler** [comment]
Hi!

Is that the same machine you used before or another one? I believe if it would fallback to Intel graphics card, it would work. 

Can you try to compile your project with customized dotrix build:
[This line](https://github.com/lowenware/dotrix/blob/d7790a8e5692fcee4c9d2c34b494b13c8920bcc6/dotrix_core/src/application.rs#L196) has to be changed with 
```
power_preference: wgpu::PowerPreference::HighPerformance,
```

And please let me know if it helps. If you need some support on this, I can create a branch of dotrix with such change.

Cheers

**Comment by tree786** [comment]
Hi , Thanks for info! Yes its same machine, but before i had win 8.1 installed on.
I have git cloned the repo and modified the  application.rs  file in dotrix_core to have `power_preference` to `power_preference: wgpu::PowerPreference::HighPerformance,`, and compiled however it still gives same error:
```
thread 'main' panicked at 'Failed to find an appropiate adapter', dotrix_core/src/application.rs:201:10
```
It seems i having trouble with my graphics card on ubuntu , since even running `nvidia-smi` in terminal shows this:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 760     Off  | 00000000:01:00.0 N/A |                  N/A |
| 20%   36C    P8    N/A /  N/A |    309MiB /  1996MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
"No running processes found" which is strange since it detects my card 

I can run openGL applications like blender and minetest and supertuxkart (although with blender I having issues since it not even detecting my graphics card)..Are there any special dependicies you think I might be missing, e.g. vulkan related (i installed spir-v but not change the issue)? 

Thanks

**Comment by Lowentwickler** [comment]
Could you please publish outputs of following commands:
```
ubuntu-drivers devices
```

```
lsmod | grep -i nvidia
```

```
 lshw -numeric -C display
```

```
 lspci -vnn | grep VGA
```

**Comment by tree786** [comment]
Hi

Here are the outputs:

- for `ubuntu-drivers devices` i get:
```
WARNING:root:_pkg_get_support nvidia-driver-390: package has invalid Support Legacyheader, cannot determine support level
== /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 ==
modalias : pci:v000010DEd00001187sv00001458sd00003609bc03sc00i00
vendor   : NVIDIA Corporation
model    : GK104 [GeForce GTX 760]
driver   : nvidia-driver-450-server - distro non-free
driver   : nvidia-driver-465 - distro non-free
driver   : nvidia-driver-460 - distro non-free recommended
driver   : nvidia-driver-418-server - distro non-free
driver   : nvidia-driver-390 - distro non-free
driver   : nvidia-340 - distro non-free
driver   : nvidia-driver-460-server - distro non-free
driver   : xserver-xorg-video-nouveau - distro free builtin
```

- For `lshw -numeric -C display`:
```
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: GK104 [GeForce GTX 760] [10DE:1187]
       vendor: NVIDIA Corporation [10DE]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:37 memory:da000000-daffffff memory:d0000000-d7ffffff memory:d8000000-d9ffffff ioport:e000(size=128) memory:c0000-dffff
  *-display
       description: VGA compatible controller
       product: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:412]
       vendor: Intel Corporation [8086]
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list
       configuration: driver=i915 latency=0
       resources: irq:34 memory:db400000-db7fffff memory:c0000000-cfffffff ioport:f000(size=64)
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
```

- And for `lspci -vnn | grep VGA`:
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:0412] (rev 06) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK104 [GeForce GTX 760] [10de:1187] (rev a1) (prog-if 00 [VGA controller])

```

-

**Comment by Lowentwickler** [comment]
I've recently installed latest Ubuntu on one my old laptop. It only has integrated card. And I tried to run dotrix app and had no issues, so it is most likely issue of the driver, rather than some dependency.

Have you tried this:
```
sudo ubuntu-drivers autoinstall
sudo reboot
```

**Comment by tree786** [comment]
Hmm quite strange, I tried `sudo ubuntu-drivers autoinstall` then `sudo reboot` , but same error message I get:
```
thread 'main' panicked at 'Failed to find an appropiate adapter', dotrix_core/src/application.rs:201:10
```
I might try uninstall ubuntu and reinstall again at some point

**Comment by tree786** [comment]
I'll close this for now, but I can reopen in future if something relevant to this comes up
