### ISSUE TITLE
Camera control system

### ISSUE THREAD

**Issue by Lowentwickler** [lowenware/dotrix#8]
* [x] Add `camera_control` system to `dotrix/src/camera.rs`. The system should take Input and Camera services as parametersto adjust Camera properties according to the Input
* [x] Implement a suitable way to get current state of mouse controls and coords from input manager
* [x] Implement `mouse look` feature
* [x] ~~Implement camera rotation in XZ axis with right button hold + left/right move~~
* [x] ~~Implement camera height change in Y axis with right button hold + forward/back mpve~~

**Comment by ZKpot** [comment]
What is  "mouse look feature"?

**Comment by ZKpot** [comment]
Old comments:

> Илья КарташовDec 1, 2020 9:41:18 PM
> Смотри, тут есть несколько концептуальных косяков
> Никита
> Dec 1, 2020 9:41:52 PM
> ?
> Илья Карташов
> Dec 1, 2020 9:42:27 PM
> Все эти параметры, которые ты выставляешь камере, нужно просто сохранять
> Могут отработать несколько разных систем, меняющих параметры камеры
> Никита
> Dec 1, 2020 9:43:11 PM
> тоесть это ресурсы?
> Илья Карташов
> Dec 1, 2020 9:43:12 PM
> Например, обычное позиционирование, а потом детекция колизий с потолком и землёй
> Нет, это поля структуры Camera
> Никита
> Dec 1, 2020 9:43:53 PM
> я имею ввиду, что их нужно конвертировать в ресурсы
> я думал, что камера просто будет иметь доступ к ландшафту
> а не наоборот
> Илья Карташов
> Dec 1, 2020 9:44:15 PM
> что ты называешь ресурсами?
> Никита
> Dec 1, 2020 9:44:27 PM
> ну типа данные какие, которые можно хоть откуда достать
> Илья Карташов
> Dec 1, 2020 9:44:54 PM
> нет
> Зайду с другого конца 🙂
> cgmath::Matrix4::look_at за кадр должна вызываться максимум один раз
> Может существовать масса факторов подстраивающих камеру
> Например смерть
> Алкагольное опьянение 🙂
> и т.д.
> Поэтому рассчитывай на то, что несколько систем могут изменить входные данные
> Никита
> Dec 1, 2020 9:47:38 PM
> понял
> Илья Карташов
> Dec 1, 2020 9:48:18 PM
> Матрицу VIEW можно сохранять и пересчитывать только если был вызван хоть один из сеттеров
> Сам сервис Camera должен быть простым как 3 копейки
> Получить вводные данные и по запросу рендерера посчитать матрицу
> вся основная логика должна быть в системе
> t_height ненужно отделять от target
> Если системе нужно смотреть в определённую точку, пусть указывает нужный таргет
> Никита
> Dec 1, 2020 9:53:26 PM
> тогда получается приближение и отдаление камеры это тоже сервис?
> *система
> Илья Карташов
> Dec 1, 2020 9:54:54 PM
> я думаю, что за приближение, отдаление, мауслук и камеру привязанную к цели (ту, что сделал ты) может отвечать одна система
> мауслук - это когда камера в одной точке, а движением мыши ты её наклоняешь или поворачиваешь в стороны
> Никита
> Dec 1, 2020 9:56:52 PM
> ну значит это правильно понял
> там логика такая, приближаешь камеру, если камера близко к цели, камера от 3го лица переходит в маус лук
> Илья Карташов
> Dec 1, 2020 10:00:24 PM
> у меня на тачпаде приближение и удаление не работают
> но фича прикольная
> Никита
> Dec 1, 2020 10:00:58 PM
> ну это вопросы к инпут менеджеру, с колесиком работает)
> Илья Карташов
> Dec 1, 2020 10:01:09 PM
> угу
> вместо паттерна if (...) { same_call(A,B,C) } else { same_call(D,E,F) } лучше использовать паттерн if (...) {  a = A; b = B; b = B} else { a = D; b = E; c = F } same_call (a, b, c)
> 
> let up;
> 
>         if dxz * distance >= 0.0 {
>             up = cgmath::Vector3::unit_y();
>         } else {
>             up = -cgmath::Vector3::unit_y();
>         }
> 
> 
> можно так
> l
> 
> et up =  if dxz * distance >= 0.0 {
>             cgmath::Vector3::unit_y()
>         } else {
>             -cgmath::Vector3::unit_y()
>         }
> 
> но в данном случае ещё лучше так
> let
> 
>  mut up = cgmath::Vector3::unit_y();
> if dxz * distance < 0.0 {
>   up *= -1;
> }
> но
> 
>  зачем переворачивать камеру вверх ногами?
> я думаю, нам нужны пол и потолок чтобы обкатать
> Никита
> Dec 1, 2020 10:14:03 PM
> ага нужно отграничения сделать, согласен
> Илья Карташов
> Dec 1, 2020 10:14:23 PM
> Если сделаешь ребейз, то увидишь что появился сервис Frame с методом delta()
> https://github.com/lowenware/dotrix/blob/aa53ffaba29ee94c72461d6128309c277c01c77d/examples/demo/demo.rs#L42
> GitHub
> lowenware/dotrix
> Contribute to lowenware/dotrix development by creating an account on GitHub.
> это время между кадрами, умножая его на скорость чего либо будешь получать смещение
> в радианах, метрах или в чём-то ещё
> Никита
> Dec 1, 2020 10:19:22 PM
> ок)

Blocked by #4

**Comment by Lowentwickler** [comment]
lets keep it as is now, it works well, suits our need. All further tweaks looks more game dependent to me.
