### ISSUE TITLE
Plans for audio support in future?

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#80]
Hello,

I was wondering - are there any plans for adding audio support in the future? I.e. having a simple system to playback mp3/ogg files and control volume (and possibly 3D positional audio) etc.

Also as a side note, is there a place where i can find a roadmap?

Thanks ..!

**Comment by Lowentwickler** [comment]
Hi,

we are trying to keep [the project board](https://github.com/lowenware/dotrix/projects/1) up to date. As you can find from the TODOs there, audio crate is planned, but no progress was done yet.

At this moment I am working on a terrain shading. And together with the next release I want to add an `.exile` method for entities in the world, and also doing some research on possibilities of Pipelines refactoring, to make them look more like real pipelines with nodes, connections etc. Shading is an important part and I want to do it `right` :)

Cheers!
P.S. I suggest to keep such Q&A stuff inside of the Discussions.

**Comment by tree786** [comment]
Hi, 
Ok that sounds good! especially the `.exile` method is of much need for removing disconnected clients in my current networking project. 
Sorry about openeing it here, i will open it in discussions in furture!
Thanks
