### ISSUE TITLE
Change default behaviour of the texture sampler

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#81]
Hello

When setting uv coordinates using the `Model` , there seems to be an issue of non-tiling uvs when the uv corrdinate is out of the (0.0,1.0) range. For example, I have set the uv coordinates to 10.0 in the image below:
![Screenshot_2021-06-23_15-15-07](https://user-images.githubusercontent.com/40580296/123112956-11fc4500-d436-11eb-8c42-ad9154697703.png)
But should it not tile by the scale amount (e.g. in this case tile by 10 times in the y/x direction)? I have attached the file (it uses the `demo` project you have provided in examples folder)
[uvs.tar.gz](https://github.com/lowenware/dotrix/files/6702563/uvs.tar.gz)
Thanks

**Comment by Lowentwickler** [comment]
Hi! 

This is weird. I can only suspect some missing WGPU configuration. I will check it ASAP and let you know.

Cheers

**Comment by Lowentwickler** [comment]
Hi! 

This is a configuration of sampler. If you change it in `dotrix_core/src/renderer.rs` to 
```
        ctx.sampler = Some(device.create_sampler(&wgpu::SamplerDescriptor {
            address_mode_u: wgpu::AddressMode::Repeat,
            address_mode_v: wgpu::AddressMode::Repeat,
            address_mode_w: wgpu::AddressMode::Repeat,
            mag_filter: wgpu::FilterMode::Nearest,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::FilterMode::Nearest,
            ..Default::default()
        }));
```

It will work as expected.

**Comment by tree786** [comment]
Hi, thanks for answer, I did not know that! I close now

**Comment by Lowentwickler** [comment]
The default behaviour will be  changed in the next release

**Comment by tree786** [comment]
Ok that sounds good, shall I reopen this issues as a 'Feature Request'?

**Comment by Lowentwickler** [comment]
Sure, you can. Thank you!
